Django_Project_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('product.urls', namespace='product')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views
from . import api_views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'customer'

api_urls = [
    path('user/', api_views.UserListView.as_view()),
    path('user/create/', api_views.UserCreateView.as_view()),
    path('user/update/<int:pk>/', api_views.UserUpdateView.as_view()),
    path('user/delete/<int:pk>/', api_views.UserDeleteView.as_view()),

    path('address/', api_views.AddressListView.as_view()),
    path('address/create/', api_views.AddressCreateView.as_view()),
    path('address/update/<int:pk>/', api_views.AddressUpdateView.as_view()),
    path('address/delete/<int:pk>/', api_views.AddressDeleteView.as_view()),

    path('token-auth/', obtain_auth_token),
]

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
    path('test/', TemplateView.as_view(template_name='text.html')),
    path('contact/', views.contact, name='contact'),
    path('api/', include(api_urls)),
    # path('user/', UserListApi.as_view(), name='user'),
    # path('user/<int:pk>', UserDetailApi.as_view(), name='user'),
    # path('Address/',AddressListApi.as_view(), name='user'),
    # path('Address/<int:pk>', AddressDetailApi.as_view(), name='user'),
    ]

customer/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.conf import settings
from core.models import BaseModel
from .managers import MyUserManager
from django.db.models.signals import post_save

from django.utils.translation import gettext as _


class User(AbstractBaseUser):
    first_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('first_name')

                                  )
    last_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('last_name')
                                 )
    email = models.CharField(max_length=100, unique=True, verbose_name=_('Email'))
    phone = models.CharField(max_length=100, verbose_name=_('phone'))
    date_of_birth = models.DateField(blank=True, null=True, verbose_name=_('date_of_birth'),
                                    )
    is_active = models.BooleanField(default=True)
    objects = MyUserManager()
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    def __str__(self):
        return str(self.first_name)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


# class Register(User):
#    pass
#
# class Edit_Customer(User):
#     pass

class Address(BaseModel):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', verbose_name=_('owner'),
                              help_text=_('enter your owner'))
    lat = models.FloatField(blank=True, null=True, verbose_name=_('lat'), help_text=_('enter your lat'))
    lng = models.FloatField(blank=True, null=True, verbose_name=_('lng'), help_text=_('enter your lng'))
    country = models.CharField(max_length=50, verbose_name=_('country'), help_text=_('enter your country'))
    city = models.CharField(max_length=50, verbose_name=_('city'), help_text=_('enter your city'))
    State = models.CharField(max_length=50, verbose_name=_('state'), help_text=_('enter your state'))  # استان
    description = models.TextField(blank=True, null=True, verbose_name=_('description'),
                                   help_text=_('enter your description'))  # مشخصات دقیق آدرس
    zip_code = models.CharField(max_length=50, verbose_name=_('zip_code'), help_text=_('enter your zop_cide'))
    Alley = models.CharField(max_length=50, verbose_name=_('Alley'), help_text=_('enter your Alley'))  # کوچه
    Plaque = models.CharField(max_length=50, verbose_name=_('plaque'), help_text=_('enter your plaque'))  # پلاک

    # class Meta:
    #     ordering = ('city',)
    #     verbose_name_plural = 'Address'

    def __str__(self):
        return str(self.owner)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('user'))
    phone = models.CharField(max_length=100, verbose_name=_('phone'))
    address = models.CharField(max_length=300, verbose_name=_('address'), null=True, blank=True)

    def __str__(self):
        return str(self.user)


def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(save_profile_user, sender=User)

customer/forms.py
from django import forms
from .models import User, Profile
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'phone', 'password1')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords must match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField

    class Meta:
        model = User
        fields = ('email', 'phone', 'password')

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'address']

customer/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.mail import EmailMessage

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

from customer.serializers import *


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in successfully', 'success')
                return redirect('product:home')
            else:
                messages.error(request, 'username or password is wrong', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'customer/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'you logged out successfully', 'success')
    return redirect('product:home')


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(cd['email'], cd['phone'], cd['password'])

            user.save()
            messages.success(request, 'you registred successfully', 'success')
            return redirect('product:home')
    else:
        form = UserRegistrationForm()
        return render(request, 'customer/register.html', {'form': form})


@login_required(login_url='customer:login')
def user_profile(request):
    profile = Profile.objects.get(user_id=request.user.id)
    return render(request, 'customer/profile.html', {'profile': profile})


@login_required(login_url='customer:login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if user_form and profile_form.is_valid():
            # user_form.save()
            profile_form.save()
            messages.success(request, 'update successfully', 'success')
            return redirect('customer:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'customer/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password changed successfully', 'success')
            return redirect('customer:profile')
        else:
            messages.error(request, 'Wrong password', 'danger')
            return redirect('customer:change')

    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'customer/change.html', {'form': form})


def contact(request):
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        msg = request.POST['message']
        body = subject + '\n' + email + '\n' + msg
        form = EmailMessage(
            'contact form',
            body,
            'test',
            ('m.chekave.jazireh@gmail.com',),
        )
        form.send(fail_silently=False)
    return render(request, 'customer/contact.html')

customer/templates/customer/change.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}

        {% trans 'change' %}

{% endblock %}
{% block css %}


    <link href="{% static 'customer/update.css' %}" rel="stylesheet">


{% endblock %}

{% block content %}

{#    <h3>change password</h3><hr/>#}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button  type="submit"  class="btn btn-primary" value="change">{% trans 'Change' %}</button>
    </form>

{% endblock %}

customer/templates/customer/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}

        {% trans 'contact' %}

{% endblock %}
{% block content %}
    <div class="container" style="width: 70%">
        <div class="card bg-dark mt-5 p-5">
            <form action="{% url 'customer:contact' %}" method="post" >
                {% csrf_token %}
                <h3 class="text-center" style="color:goldenrod">{% trans 'contact by' %}</h3>
                <div class="row mt-3">
                    <div class="col-6">
                        <input type="text" class="form-control" placeholder="subject" name="subject">
                    </div>
                     <div class="col-6">
                        <input type="email" class="form-control" placeholder="email" name="email">
                    </div>
                </div>

                <div class="row mt-3">
                    <textarea name="message"  rows="4" class="form-control" style="margin-left: 15px; margin-right: 15px" placeholder="message"></textarea>
                </div>
                <button type="submit" class="btn btn-danger mt-3">{% trans 'Send Email' %}</button>
            </form>
        </div>
    </div>
{% endblock %}

customer/templates/customer/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}

        {% trans 'login' %}

{% endblock %}
{% block css %}


    <link href="{% static 'customer/register.css' %}" rel="stylesheet">


{% endblock %}

{% block content %}

{#    <p>login page</p>#}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button  type="submit"  class="btn btn-primary" value="login">{% trans 'Login' %}</button>
    </form>
{% endblock %}

customer/templates/customer/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}

    {% trans 'profile' %}

{% endblock %}
{% load static %}
{% block content %}

{% block css %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="{% static 'customer/profile.css' %}" rel="stylesheet">
{% endblock %}

<div class="container-fluid">
    <div class="row">
        <div class="col-3 p-2" style="min-height: 85vh">
            <div class="panel text-center " id="side-panel">
                <div class="card">
                    <div class="card-header m-0 p-0">
                        <a class="card-link " data-toggle="collapse" href=""><button class="btn btn-block btn-secondary">{% trans 'Profile' %}</button>
                        </a>
                    </div>
                </div>

                <div class="card mt-2 ">
                    <div class="card-header m-0 p-0">
                        <a class="card-link " data-toggle="collapse" href="#users"><button class="btn btn-block btn-secondary">
                            {% trans 'Users' %}</button>
                        </a>
                    </div>
                    <div id="users" class="collapse " data-parent="#side-panel">
                        <div class="list-group-item">
                            <button class="btn btn-block btn-light"><a href="{% url 'customer:update' %}">{% trans 'Update User' %}</a></button>
                            <button class="btn btn-block btn-light"><a href="{% url 'customer:change' %}">{% trans 'Change Password' %}</a></button>


                        </div>
                    </div>
                </div>


    </div>
</div>
    <div class="col-9 bg-secondary " style="height: 550px">

           <table style="color: white; font-size: 15px">
{% csrf_token %}
<tr >
    <th >first name: {{ profile.user.first_name }}</th>
</tr>
    <tr>
    <th>last name: {{ profile.user.last_name }}</th>
</tr>
<tr>
    <th>phone: {{ profile.user.phone }}</th>
</tr>
<tr>
    <th>Email: {{ profile.user.email }}</th>
</tr>
{#<tr>#}
{#    <th>Birth of Date: {{ profile.user.date_of_birth }}</th>#}
{#</tr>#}
<tr>
    <th>Address: {{ profile.address }}</th>
</tr>
</table>
    </div>
    </div>
</div>
{% endblock %}

customer/templates/customer/register.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}

        {% trans 'register' %}

{% endblock %}

{% block css %}


    <link href="{% static 'customer/register.css' %}" rel="stylesheet">


{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button  type="submit"  class="btn btn-primary" value="register">{% trans 'register' %}</button>
    </form>
{% endblock %}

customer/templates/customer/update.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
        {% trans 'update' %}
{% endblock %}

{% block css %}


    <link href="{% static 'customer/update.css' %}" rel="stylesheet">


{% endblock %}

{% block content %}
{#<h2>update profile</h2>#}
<form action="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button  type="submit"  class="btn btn-primary" value="Update">{% trans 'Update' %}</button>
</form>
{% endblock %}