Django_Project_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('product.urls', namespace='product')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path, include
from . import views
from . import api_views

app_name = 'orders'

api_urls = [
    path('order/', api_views.OrderListView.as_view()),
    path('order/create/', api_views.OrderCreateView.as_view()),
    path('order/update/<int:pk>/', api_views.OrderUpdateView.as_view()),
    path('order/delete/<int:pk>/', api_views.OrderDeleteView.as_view()),

    path('orderitem/', api_views.OrderItemListView.as_view()),
    path('orderitem/create/', api_views.OrderItemCreateView.as_view()),
    path('orderitem/update/<int:pk>/', api_views.OrderItemUpdateView.as_view()),
    path('orderitem/delete/<int:pk>/', api_views.OrderItemDeleteView.as_view()),

    path('coupen/', api_views.CouponView.as_view()),

]

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
    path('api-order/', include(api_urls)),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart_session import Cart
from product.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST


def detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'])
    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% trans 'detail' %}
{% endblock %}
{% block content %}
    <table class="table ">
        <thead style="color: #000000">
        <tr>
            <th scope="col">{% trans 'Number' %} </th>
            <th scope="col">{% trans 'Product' %}</th>
            <th scope="col">{% trans 'Quantity' %}</th>
            <th scope="col">{% trans 'Unit Price' %}</th>
            <th scope="col">{% trans 'Total Price' %}</th>
            <th scope="col">{% trans 'Remove' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td><i class="gb gb_remove_circle mx-2 gb_s18 text-danger pointer remove_item"></i>
                    <span>{{ item.quantity }}</span>
                    <i class="gb gb_add_circle  mx-2 gb_s18 text-success pointer add_item"></i></td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td><a id="id" href="{% url 'cart:cart_remove' item.product.id %}">Remove</a></td>

            </tr>
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="3"></td>
            <td>{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'orders:create' %}" class="btn btn-primary">Checkout</a>

{% endblock %}

{% block extrajs %}
    <script>
        $('.add_item').click(function () {
            $.ajax({
                url: 'cart:cart_add',
                type: 'PATCH', data: {},
                success: function (response) {


                }
            });
            let num = Number($(this).parent().children('span').text()) + 1
                    $(this).parent().children('span').text(String(num))
        })

        $('.remove_item').click(function () {
            let num = Number($(this).parent().children('span').text()) - 1
            $(this).parent().children('span').text(String(num))
        })

    </script>


{% endblock %}