Django_Project_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('product.urls', namespace='product')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

product/urls.py
from django.urls import path, include
from . import views
from .views import  ProductlistAPiView, ProductPUTApi
from django.conf import settings
from django.conf.urls.static import static
from . import api_views

app_name = 'product'

api_urls = [
    path('product/', api_views.ProductListView.as_view()),
    path('product/create/', api_views.ProductCreateView.as_view()),
    path('product/update/<int:pk>/', api_views.ProductUpdateView.as_view()),
    path('product/delete/<int:pk>/', api_views.ProductDeleteView.as_view()),

    path('category/', api_views.CategoryListView.as_view()),
    path('category/create/', api_views.CategoryCreateView.as_view()),
    path('category/update/<int:pk>/', api_views.CategoryUpdateView.as_view()),
    path('category/delete/<int:pk>/', api_views.CategoryDeleteView.as_view()),

]

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:slug>/', views.home, name='category filter'),
    path('product_list/', views.product_list_api),
    path('product_detail_api/<str:pk>', ProductPUTApi.as_view()),
    path('search/', views.product_search, name='product_search'),
    path('product-api/', include(api_urls)),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.conf import settings
from core.models import BaseModel


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('name'), help_text=_('enter your name'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name=_('slug'), help_text=_('slug in project'))

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:category filter', args=[self.slug, ])


class Discount(BaseModel):
    title = models.CharField(max_length=100, verbose_name=_('title'), help_text=_('enter your tittle'))
    Deduction_from_the_price = models.IntegerField(verbose_name=_('Deduction_from_the_price'),
                                                   help_text=_('enter your Deduction_from_the_price'))  # کسر از قیمت
    Cash = models.IntegerField(verbose_name=_('Cash'),
                               help_text=_('enter your Cash'))  # نقدی
    description = models.TextField(verbose_name=_('description'), help_text=_('Additional product description'))

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Discounts'

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name=_('products'),
                                 help_text=_('category'))
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, verbose_name=_('discount'),
                                 help_text=_('discount'), blank=True, null=True)
    name = models.CharField(max_length=200, verbose_name=_('name'), help_text=_('enter your name'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name=_('slug'), help_text=_('slug in project'))
    image = models.ImageField(upload_to='products/%Y/%m/%d/', help_text=_('enter your image'))
    description = models.TextField(verbose_name=_('description'), help_text=_('Additional product description'))
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_('price'), help_text=_('price'))

    available = models.BooleanField(default=True, verbose_name=_('available'), help_text=_('This product is available '
                                                                                           'in the store'))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.slug, ])
    #
    # def final_price(self):
    #     disc = self.discount or 0
    #     discounted_price = self.price * disc // 100
    #     return self.price - discounted_price


class Gallery(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('name'))
    image = models.ImageField(upload_to='gallery/', blank=True, verbose_name=_('image'))

    def __str__(self):
        return self.name

product/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

product/views.py
from rest_framework import generics
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from cart.forms import CartAddForm
from .models import Product, Category, Gallery
from django.utils.translation import gettext as _
from .forms import SearchForm

from .serializers import ProductSerializer


def home(request, slug=None):
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    gallery = Gallery.objects.all()
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    return render(request, 'product/home.html', {_('products'): products, _('categories'): categories, _('gallery'): gallery})


def product_detail(request, slug):
    products = get_object_or_404(Product, slug=slug)
    # products = Product.objects.all()
    form = CartAddForm()
    return render(request, 'product/detail.html', {_('products'): products, _('form'): form})


@csrf_exempt
@api_view(['GET', 'POST'])
def product_list_api(request):
    if request.method == 'GET':
        product = Product.objects.all()
        p = ProductSerializer(product, many=True)
        return JsonResponse({'product': p.data})

    elif request.method == 'POST':
        p = ProductSerializer(data=request.POST)
        if p.is_valid():
            p.save()
            return JsonResponse(p.data)
        else:
            return JsonResponse(p.errors)


class ProductlistAPiView(generics.ListCreateAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()


class ProductPUTApi(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()


def product_search(request):
    products = Product.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data is not None:
                products = products.filter(name__exact=data)
            return render(request, 'product/detail.html',{'products': products, 'form': form})

product/templates/product/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}

        {% trans ' detail' %}

{% endblock %}
{% block content %}

     <div class="container-fluid">
    <div class="row-cols-4">
    <h3>{{ products.name }}</h3>
    <small>{{ product.created }}</small>
    <img src="{{ products.image.url }}" class="card-img-top" style="width: 250px;height: 250px; text-align: center;box-shadow: 1px 2px dimgrey" alt="...">
    <p>{{ products.description }}</p><br/><br/>
    <form action="{% url 'cart:cart_add' products.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" style="width: 8rem" value="add to cart">
    </form>
    </div>
     </div>
{% endblock %}

product/templates/product/home.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
        {% trans ' home' %}
{% endblock %}
{% load static %}

{% block css %}

    <link href="{{ 'home.html'}}" rel="stylesheet">
{% endblock %}
{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}


{% block content %}

    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="box-shadow: 1px 2px dimgrey,1px 2px dimgrey">
        <ol class="carousel-indicators">
            <li  data-bs-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li  data-bs-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li  data-bs-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            {% for i in gallery %}
            <div class="carousel-item {% if forloop.first %} active {% endif %}">
                <img src="{{ i.image.url }}" style="width: auto;height: 300px" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>{{ i.name }}</h5>

                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button"
                data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button"
                data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div><br><br>


{% for category in categories %}
    <a href="{{ category.get_absolute_url }}" class="btn btn-primary">{{ category.name }}</a>
{% endfor %} <br/><br/><br/>


{% for product in products %}
 <div class="card" style="width: 18rem; display: inline-block;margin-left: 2rem; box-shadow: 1px 2px dimgrey">
    <img src="{{ product.image.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
    </div>
 </div>

{% endfor %}


{% endblock %}

product/templates/product/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ product.name }}</h3>
{% endblock %}