Django_Project_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('product.urls', namespace='product')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views
from . import api_views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'customer'

api_urls = [
    path('user/', api_views.UserListView.as_view()),
    path('user/create/', api_views.UserCreateView.as_view()),
    path('user/update/<int:pk>/', api_views.UserUpdateView.as_view()),
    path('user/delete/<int:pk>/', api_views.UserDeleteView.as_view()),

    path('address/', api_views.AddressListView.as_view()),
    path('address/create/', api_views.AddressCreateView.as_view()),
    path('address/update/<int:pk>/', api_views.AddressUpdateView.as_view()),
    path('address/delete/<int:pk>/', api_views.AddressDeleteView.as_view()),

    path('token-auth/', obtain_auth_token),
]

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
    path('test/', TemplateView.as_view(template_name='text.html')),
    path('contact/', views.contact, name='contact'),
    path('api/', include(api_urls)),
    # path('user/', UserListApi.as_view(), name='user'),
    # path('user/<int:pk>', UserDetailApi.as_view(), name='user'),
    # path('Address/',AddressListApi.as_view(), name='user'),
    # path('Address/<int:pk>', AddressDetailApi.as_view(), name='user'),
    ]

product/urls.py
from django.urls import path, include
from . import views
from .views import  ProductlistAPiView, ProductPUTApi
from django.conf import settings
from django.conf.urls.static import static
from . import api_views

app_name = 'product'

api_urls = [
    path('product/', api_views.ProductListView.as_view()),
    path('product/create/', api_views.ProductCreateView.as_view()),
    path('product/update/<int:pk>/', api_views.ProductUpdateView.as_view()),
    path('product/delete/<int:pk>/', api_views.ProductDeleteView.as_view()),

    path('category/', api_views.CategoryListView.as_view()),
    path('category/create/', api_views.CategoryCreateView.as_view()),
    path('category/update/<int:pk>/', api_views.CategoryUpdateView.as_view()),
    path('category/delete/<int:pk>/', api_views.CategoryDeleteView.as_view()),

]

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:slug>/', views.home, name='category filter'),
    path('product_list/', views.product_list_api),
    path('product_detail_api/<str:pk>', ProductPUTApi.as_view()),
    path('search/', views.product_search, name='product_search'),
    path('product-api/', include(api_urls)),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/inc/footer.html
{% block script %}
    {% load i18n %}
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-facebook-f "></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-linkedin"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
        ><i class="fa fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <p class="text-white" href="#">{% trans '© 2021 Copyright: Store_Dez.com' %}</p>
  </div>
  <!-- Copyright -->
</footer>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tag }}">{{ msg.tag }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
{% load i18n %}
<link rel="stylesheet" href="{% static 'navbar.css' %}">
<h5 style="background-color: #4e555b;color: #bdc1c2">Store Dez</h5>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">

        <a class="nav-item nav-link active" href="{% url 'product:home' %}">{% trans 'home' %}</a>
        {% if request.user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'customer:profile' %}">{% trans 'Profile' %}</a>
            <a class="nav-item nav-link active" href="{% url 'customer:logout' %}">{% trans 'logout' %}</a>
        {% else %}
            <a class="nav-item nav-link active" href="{% url 'customer:login' %}">{% trans 'login' %}</a>
            <a class="nav-item nav-link active" href="{% url 'customer:register' %}">{% trans 'Register' %}</a>
        {% endif %}
    <a class="nav-item nav-link active " style="margin-left: 800px" href="{% url 'customer:contact' %}">{% trans 'Contact us page'%}</a>
    </div>

</nav>